version: "3.0"
services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 3700
      MYSQL_USER: ben
      MYSQL_PASSWORD: lolo5050
      TZ: Asia/Seoul
    ports: 
      - 3306:3306
      
  account:
    build: 
       context: /
       dockerfile: Dockerfile
    image: account
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/accounting?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ben
      SPRING_DATASOURCE_PASSWORD: lolo5050
    restart: on-failure
    ports :
    - 8080:8080
    links: 
      - db
    depends_on: 
      - db

